import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, WidthType } from 'docx';
import { saveAs } from 'file-saver';
import { Project } from '../types';

export class ExportService {
  /**
   * Export SRS as formatted Markdown (.md)
   */
  static exportMarkdown(project: Project): void {
    const mdContent = generateSRSMarkdown(project);
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    saveAs(blob, `${slugify(project.name)}_IEEE_SRS.md`);
  }

  /**
   * Export SRS as plain text (.txt)
   */
  static exportText(project: Project): void {
    const txtContent = generateSRSMarkdown(project);
    const blob = new Blob([txtContent], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, `${slugify(project.name)}_IEEE_SRS.txt`);
  }

  /**
   * Export SRS as professional IEEE PDF using jsPDF
   */
  static exportPDF(project: Project): void {
    const doc = new jsPDF();
    const margin = 15;
    let y = 20;

    // Title Page
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(0, 114, 255); // Neon Blue
    doc.text('SOFTWARE REQUIREMENT SPECIFICATION', margin, y);

    y += 10;
    doc.setFontSize(16);
    doc.setTextColor(240, 240, 240);
    doc.text(`Project: ${project.name}`, margin, y);

    y += 8;
    doc.setFontSize(11);
    doc.setTextColor(150, 150, 160);
    doc.text(`Domain: ${project.domain} | Standard: IEEE 830-1998 / 29148-2018`, margin, y);
    doc.text(`Generated by RequireX AI Suite | Date: ${new Date().toLocaleDateString()}`, margin, y + 6);

    y += 20;
    doc.setLineWidth(0.5);
    doc.setDrawColor(0, 240, 255);
    doc.line(margin, y, 195, y);

    y += 15;
    // Section 1: Introduction
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 240, 255);
    doc.text('1. Introduction', margin, y);

    y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50, 50, 50);
    doc.text(`1.1 Purpose: This document provides a complete IEEE specification for ${project.name}.`, margin, y);

    y += 6;
    doc.text(`1.2 Scope: Covers core functional requirements, quality constraints, user stories, and test cases.`, margin, y);

    y += 12;
    // Section 2: Functional Requirements
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 240, 255);
    doc.text('2. Functional Requirements', margin, y);

    y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50, 50, 50);

    const functionalReqs = project.requirements.filter(r => r.category === 'Functional');
    if (functionalReqs.length === 0) {
      doc.text('No functional requirements recorded.', margin, y);
      y += 8;
    } else {
      functionalReqs.forEach(req => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        const text = `• [${req.id}] ${req.improvedText || req.description}`;
        const splitText = doc.splitTextToSize(text, 175);
        doc.text(splitText, margin, y);
        y += splitText.length * 5 + 3;
      });
    }

    y += 8;
    // Section 3: Non-Functional Requirements
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 240, 255);
    doc.text('3. Non-Functional & Technical Requirements', margin, y);

    y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50, 50, 50);

    const nonFuncReqs = project.requirements.filter(r => r.category !== 'Functional');
    nonFuncReqs.forEach(req => {
      if (y > 270) { doc.addPage(); y = 20; }
      const text = `• [${req.id}] (${req.category}) ${req.improvedText || req.description}`;
      const splitText = doc.splitTextToSize(text, 175);
      doc.text(splitText, margin, y);
      y += splitText.length * 5 + 3;
    });

    // Save PDF
    doc.save(`${slugify(project.name)}_IEEE_SRS.pdf`);
  }

  /**
   * Export SRS as Word (.docx) document using docx library
   */
  static exportDOCX(project: Project): void {
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: `Software Requirement Specification (SRS)`,
            heading: HeadingLevel.TITLE,
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Project Name: `, bold: true }),
              new TextRun({ text: project.name }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Domain: `, bold: true }),
              new TextRun({ text: project.domain }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Specification Standard: `, bold: true }),
              new TextRun({ text: `IEEE Std 830-1998 / 29148-2018` }),
            ],
          }),
          new Paragraph({ text: '' }), // Spacer

          new Paragraph({
            text: `1. Introduction & Project Description`,
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: project.description || 'No description provided.',
          }),
          new Paragraph({ text: '' }),

          new Paragraph({
            text: `2. Requirements Inventory`,
            heading: HeadingLevel.HEADING_1,
          }),
          ...project.requirements.map(req => 
            new Paragraph({
              children: [
                new TextRun({ text: `[${req.id}] `, bold: true, color: '0072FF' }),
                new TextRun({ text: `(${req.category}) `, italics: true }),
                new TextRun({ text: req.improvedText || req.description }),
              ]
            })
          ),

          new Paragraph({ text: '' }),
          new Paragraph({
            text: `3. Agile User Stories`,
            heading: HeadingLevel.HEADING_1,
          }),
          ...project.userStories.map(us => 
            new Paragraph({
              children: [
                new TextRun({ text: `[${us.id}] As a `, bold: true }),
                new TextRun({ text: us.asA }),
                new TextRun({ text: `, I want to ` }),
                new TextRun({ text: us.iWantTo }),
                new TextRun({ text: ` so that ` }),
                new TextRun({ text: us.soThat }),
              ]
            })
          ),
        ],
      }],
    });

    Packer.toBlob(doc).then(blob => {
      saveAs(blob, `${slugify(project.name)}_IEEE_SRS.docx`);
    });
  }
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/(^-|-$)+/g, '');
}

export function generateSRSMarkdown(project: Project): string {
  const dateStr = new Date().toLocaleDateString();
  return `# Software Requirement Specification (SRS)
## Project Name: ${project.name}
- **Domain**: ${project.domain}
- **Standard**: IEEE Std 830-1998 / ISO/IEC/IEEE 29148-2018
- **Generated By**: RequireX AI Suite
- **Date**: ${dateStr}

---

## 1. Introduction

### 1.1 Purpose
This Software Requirement Specification (SRS) document details the functional, non-functional, security, and quality requirements for the **${project.name}** software system.

### 1.2 Scope
${project.description || 'System specification covers all core software sub-modules, database integrations, external interfaces, and security controls.'}

### 1.3 Definitions & Acronyms
- **SRS**: Software Requirement Specification
- **IEEE**: Institute of Electrical and Electronics Engineers
- **RTM**: Requirement Traceability Matrix
- **PNR**: Passenger Name Record (if applicable)

---

## 2. Requirements Specification

### 2.1 Functional Requirements
${project.requirements.filter(r => r.category === 'Functional').map(r => `#### [${r.id}] ${r.title}
- **Category**: ${r.category} | **Priority**: ${r.priority}
- **Specification**: ${r.improvedText || r.description}
${r.issues.length > 0 ? `- **Quality Audit Notes**: ${r.issues.map(i => i.problem).join('; ')}` : ''}
`).join('\n')}

### 2.2 Non-Functional Requirements
${project.requirements.filter(r => r.category !== 'Functional').map(r => `#### [${r.id}] ${r.title}
- **Category**: ${r.category} | **Priority**: ${r.priority}
- **Specification**: ${r.improvedText || r.description}
`).join('\n')}

---

## 3. Agile User Stories

${project.userStories.map(us => `### [${us.id}] User Story (Priority: ${us.priority}, Story Points: ${us.storyPoints})
**As a** ${us.asA}  
**I want to** ${us.iWantTo}  
**So that** ${us.soThat}  

**Acceptance Criteria**:
${us.acceptanceCriteria.map(ac => `- ${ac}`).join('\n')}
`).join('\n')}

---

## 4. Textual Use Cases

${project.useCases.map(uc => `### [${uc.id}] ${uc.title}
- **Actors**: ${uc.actors.join(', ')}
- **Preconditions**: ${uc.preconditions.join('; ')}
- **Postconditions**: ${uc.postconditions.join('; ')}
- **Main Flow**:
${uc.mainFlow.map(step => `  ${step}`).join('\n')}
`).join('\n')}

---

## 5. Automated Test Matrix

| Test ID | Category | Description | Input | Expected Output | Status |
|---|---|---|---|---|---|
${project.testCases.map(tc => `| ${tc.id} | ${tc.category} | ${tc.description} | ${tc.inputData} | ${tc.expectedOutput} | ${tc.status} |`).join('\n')}

---

## 6. Risk Analysis & Mitigation

${project.risks.map(rsk => `- **[${rsk.id}] ${rsk.title}** (${rsk.category}): Impact: ${rsk.impact}, Probability: ${rsk.probability}.  
  *Mitigation*: ${rsk.mitigation}
`).join('\n')}

---

## 7. Requirement Traceability Matrix (RTM)

| Requirement ID | Title | Use Case | Test Cases | Coverage Status |
|---|---|---|---|---|
${project.requirements.map(req => {
  const uc = project.useCases.find(u => u.requirementId === req.id)?.id || 'N/A';
  const tcs = project.testCases.filter(t => t.requirementId === req.id).map(t => t.id).join(', ') || 'None';
  return `| ${req.id} | ${req.title} | ${uc} | ${tcs} | Covered |`;
}).join('\n')}

---
*End of SRS Document - Generated by RequireX*
`;
}
